### PR TITLE
Changed circle graph to allow for multiple arcs.

### PR DESCRIPTION
**Pull request by umamialex**

### CODE REVIEW

**Comment by nubs** [comment]
rather than doing separate commits for the JIRA stuff, can you just stick it down in a new paragraph in your main commit's comment?

**Comment by umamialex** [comment]
Yah I just keep forgetting...

**Comment by nubs** [comment]
LGTM

**Comment by nubs** [comment]
you can amend your commits.  `git commit --amend` or `git rebase -i` and use the `reword` option

**Pull request merged**
