### PR TITLE
improve logic for determining if label should be shown

### PR DESCRIPTION
**Pull request by evanlucas**
# LC-719

### CODE REVIEW

**Comment by nubs** [comment]
The commit message doesn't seem to match up with the contents? :p  Can you put some details in there about what this magic number change does?

**Comment by nubs** [comment]
Also, this'll need a version bump

**Comment by evanlucas** [comment]
Commit message updated.

**Comment by attack7** [comment]
LGTM

**Comment by nubs** [comment]
LGTM

**Pull request merged**
